Toggle row action menu
KevinVandy/mantine-react-table pull request #133
Opened 2023-09-22 21:02 UTC by alessandrojcm

* Refactored MRT_ToggleRowActionMenuButton
* Also omitted the `style` prop from `HTMLPropsRef` as the `MantineStyleProps` already has `CSSProperties` as part of its union type, this was causing type errors. Not sure about this so let me know if it's not correct

2023-09-22 21:06 UTC, KevinVandy requested changes

2023-09-22 21:06 UTC, KevinVandy commented on packages/mantine-react-table/src/buttons/MRT_ToggleRowActionMenuButton.tsx
> +  className,
Small thing, class name needs to only come from mantineProps, not the literal props of this internal component

2023-09-22 21:12 UTC, alessandrojcm commented on packages/mantine-react-table/src/buttons/MRT_ToggleRowActionMenuButton.tsx
> +  className,
Is there a `mantineProps` for this component? Can't seem to find it

2023-09-23 15:32 UTC, KevinVandy approved these changes

2023-09-23 15:32 UTC, merged