feat: add multi-select option to column editVariant parameter
KevinVandy/mantine-react-table pull request #357
Opened 2024-06-13 15:35 UTC by yann-combarnous

This PR adds a multi-select option to the columnOption: 'editVariant'.

In Mantine, Select and MultiSelect have the same properties, so extending this MRT option should not bring conflicts.

2024-07-10 16:12 UTC, alessandrojcm commented
Hi @yann-combarnous thanks for your PR, please see my comments when you get a chance.

2024-07-10 19:25 UTC, yann-combarnous commented
> Hi @yann-combarnous thanks for your PR, please see my comments when you get a chance.

Sure, but not seeing any atm??

2024-07-11 08:34 UTC, alessandrojcm requested changes

2024-07-11 08:34 UTC, alessandrojcm commented on packages/mantine-react-table/src/components/inputs/MRT_EditCellTextInput.tsx
> +      // @ts-ignore
Could we try casting here instead of ts-ignore?

2024-07-11 08:35 UTC, alessandrojcm commented
> > Hi @yann-combarnous thanks for your PR, please see my comments when you get a chance.
> 
> Sure, but not seeing any atm??

Sorry forgo to tick submit review, please check now.

2024-07-11 13:40 UTC, yann-combarnous commented
> > > Hi @yann-combarnous thanks for your PR, please see my comments when you get a chance.
> > 
> > 
> > Sure, but not seeing any atm??
> 
> Sorry forgo to tick submit review, please check now.

Thx, added a fix attempt, please have a look. It also solves the previously existing `@ts-ignore` for the `Select` component.

2024-07-11 18:47 UTC, alessandrojcm approved these changes
Looks good, thanks!

2024-07-11 18:47 UTC, merged