feat: add filterTooltipValueFn option to transform the value of the filter tooltip
KevinVandy/mantine-react-table pull request #360
Opened 2024-06-14 06:19 UTC by yamadayutaka

This PR is an implementation of the feature suggestion #359.

Specify the Column Option as follows.
```ts
{
  ...
  filterTooltipValueFn: (value: any) => {
    const d = dayjs(value || '');
    return d.isValid() ? d.format('L') : '';
  },
  ...
},
```

Then, the tooltip is displayed as follows.
![image](https://github.com/KevinVandy/mantine-react-table/assets/77612853/ad489d33-7e94-4378-b069-959c4fe31fc1)

2024-07-10 16:03 UTC, alessandrojcm commented
Hi @yamadayutaka thanks for your contribution, please see the comments I left.

2024-07-11 00:58 UTC, yamadayutaka commented
Hi @alessandrojcm thanks for your reply!
But I can't check your comments.
I think you may have forgotten to "Submit review".
Could you confirm this?

2024-07-11 08:35 UTC, alessandrojcm requested changes

2024-07-11 08:35 UTC, alessandrojcm commented on packages/mantine-react-table/src/components/head/MRT_TableHeadCellFilterLabel.tsx
> +                ? (column.getFilterValue() as [])
Not sure here about the type, if the previous type was casted as `[string, string]` then it should remain so.

2024-07-11 08:35 UTC, alessandrojcm commented on packages/mantine-react-table/src/types.ts
> +  filterTooltipValueFn?: (value: any) => string,
Same here

2024-07-11 08:36 UTC, alessandrojcm commented
> Hi @alessandrojcm thanks for your reply! But I can't check your comments. I think you may have forgotten to "Submit review". Could you confirm this?

Yes apologies, please check now.

2024-07-11 09:00 UTC, yamadayutaka commented on packages/mantine-react-table/src/components/head/MRT_TableHeadCellFilterLabel.tsx
> +                ? (column.getFilterValue() as [])
Since `filterTooltipValueFn` does the conversion to string, I think the input to `filterTooltipValueFn` should remain the original data type.

2024-07-11 18:50 UTC, alessandrojcm commented on packages/mantine-react-table/src/components/head/MRT_TableHeadCellFilterLabel.tsx
> +                ? (column.getFilterValue() as [])
Ok yeah agree, do you think you could type the prop accordingly then? Basically, I´d like to avoid using `any` when possible.

2024-07-17 00:36 UTC, yamadayutaka commented on packages/mantine-react-table/src/components/head/MRT_TableHeadCellFilterLabel.tsx
> +                ? (column.getFilterValue() as [])
I added a type definition. What do you think of this?

2024-07-17 07:53 UTC, alessandrojcm commented on packages/mantine-react-table/src/components/head/MRT_TableHeadCellFilterLabel.tsx
> +                ? (column.getFilterValue() as [])
Thanks @yamadayutaka could please add it to the prop? So it'd be `filterToolValueFn?: (value: string) => string`

2024-07-17 17:05 UTC, alessandrojcm approved these changes
Sorry missed that you already typed the props (GH's UI can be very confusing sometimes...) Wil merge now thanks!

2024-07-17 17:05 UTC, merged

2024-07-18 00:32 UTC, yamadayutaka commented
Thanks for merging!