Add MRT_TableBodyEmptyRow component to render when table has no rows
KevinVandy/mantine-react-table pull request #445
Opened 2024-11-19 15:06 UTC by EdwardEB

Replace <tr> component in MRT_TableBody with MRT_TableBodyEmptyRow component, that renders a MRT_TableBodyRow when table has no rows, and can be built on and improved in the future.

By doing this, the row that renders when the table is empty has the same props as an actual data row and would add consistency, flexibility, and the ability to use features like the detail panel.

Also added EmptyRow stories, to showcase the possible uses.

2024-11-27 21:43 UTC, alessandrojcm commented
LGTM @KevinVandy I know you were a bit hesitant over discord about this, however I think these are valid use cases. @EdwardEB on top of the couple of comments that I left there: 1) Could you please update the examples to use the `useMantineReactTable` hook? 2) Add the new component to the `src/index.ts` barrel file, thanks!

2024-11-28 08:04 UTC, EdwardEB commented
@alessandrojcm I've made the changes you requested, but I could not find any comments on the files changed? Did you leave comments somewhere else that I may have missed?

2024-11-28 08:46 UTC, alessandrojcm requested changes

2024-11-28 08:46 UTC, alessandrojcm commented on packages/mantine-react-table/stories/features/EmptyRow.stories.tsx
> +      renderDetailPanel={({ table, row, internalEditComponents }) => (
Could the form be added in the `renderEmptyRowsFallback` instead? Makes more sense that way IMO.

2024-11-28 08:46 UTC, alessandrojcm commented on packages/mantine-react-table/stories/features/EmptyRow.stories.tsx
> +        onContextMenu: showContextMenu([
Would this not add a context menu for _every_ row?

2024-11-28 08:47 UTC, alessandrojcm commented
> @alessandrojcm I've made the changes you requested, but I could not find any comments on the files changed? Did you leave comments somewhere else that I may have missed?

Sorry I always forget to click start review check now please

2024-11-28 09:13 UTC, EdwardEB commented on packages/mantine-react-table/stories/features/EmptyRow.stories.tsx
> +      renderDetailPanel={({ table, row, internalEditComponents }) => (
The form could be added in the empty rows fallback, but the feature that I'm trying to showcase is a form in the detail panel, when the grid has rows (change a record) and when the grid is empty (add a record).

Maybe I should add another story where the table has rows, with a form in the detail panel?

2024-11-28 09:13 UTC, EdwardEB commented on packages/mantine-react-table/stories/features/EmptyRow.stories.tsx
> +        onContextMenu: showContextMenu([
It would not, the useContextMenu hook is called only once, each row will have a onContextMenu callback, that will render the same context menu when the row is right clicked. I personally prefer react-contexify, because the developer has control over where to mount the context menu, but the important thing is that I need the common props in the no row component.

2024-11-28 09:42 UTC, alessandrojcm commented on packages/mantine-react-table/stories/features/EmptyRow.stories.tsx
> +      renderDetailPanel={({ table, row, internalEditComponents }) => (
Yes that would be useful thanks

2024-11-28 10:57 UTC, EdwardEB commented on packages/mantine-react-table/stories/features/EmptyRow.stories.tsx
> +      renderDetailPanel={({ table, row, internalEditComponents }) => (
I've changed the story to showcase form in detail panel when table is empty, and when there are rows.
I get the feeling that this story should move to editing examples, it feels odd here.

2024-11-29 10:21 UTC, alessandrojcm commented on packages/mantine-react-table/stories/features/EmptyRow.stories.tsx
> +      renderDetailPanel={({ table, row, internalEditComponents }) => (
Yes I think you are right, could you move it then please?

2024-11-29 12:04 UTC, EdwardEB commented on packages/mantine-react-table/stories/features/EmptyRow.stories.tsx
> +      renderDetailPanel={({ table, row, internalEditComponents }) => (
Cool, I've moved the story to the editing examples. It makes much more sense there.
Thanks for your help.

2024-12-01 20:55 UTC, alessandrojcm approved these changes
Looks good now, thanks!

2024-12-01 20:55 UTC, merged